apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-cpu-scaler
  namespace: default
spec:
  schedule: "*/3 * * * *"   # every 3 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-inference
            image: ramyashalini/cloud-inference-job
            imagePullPolicy: Always
          restartPolicy: OnFailure
