apiVersion: v1
kind: Service
metadata:
  name: cloud-auto-service
spec:
  selector:
    app: cloud-auto
  ports:
    - protocol: TCP        
      port: 80           # Internal Kubernetes service port
      targetPort: 5000   # container port inside the pod
      nodePort: 30007    # actual port exposed on llocalhost (30000-32767)
  type: NodePort 