apiVersion: v1
kind: Service
metadata:
  name: cloud-auto-service
spec:
  selector:
    app: cloud-auto
  ports:
    - protocol: TCP
      port: 80      # External port (ClusterIP, NodePort, LoadBalancer)
      targetPort: 5000  # Match the containerPort in deployment.yaml
  type: LoadBalancer  # Change to NodePort if testing locally
