

FROM python:3.12-slim

WORKDIR /app

# Copy only the AI module and fetch_metrics
COPY src/ai_module/ ./ai_module/
COPY src/ai_module/fetch_metrics.py ./ai_module/

RUN pip install requests

CMD ["python", "ai_module/inference.py"]
